name: Setup server connection
description: This action setup the config to connect to vps via ansible and produces one backup
runs:
  using: "composite"
  steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Get config
      run: |
        echo "${{ vars.MINECRAFT_CONFIG }}" > .env
        echo "${{ secrets.HOSTS }}" > hosts
        echo "${{ secrets.PRIVATE_KEY }}" > private-key
        chmod +x ./bootstrap.sh
        chmod 600 private-key

    - name: Backup
      run: ansible-playbook --tags="backup" ${{ env.ANSIBLE_CUSTOM_ARGS }}

    - name: Upload backup
      uses: actions/upload-artifact@v3
      with:
        name: backup-$NOW
        path: backups/${{ secrets.VPS_HOSTNAME }}/home/${{ secrets.VPS_USER }}/*.zip
    