version: "3.8"
services:
  plugsy:
    image: rancher/rancher
    container_name: rancher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    restart: unless-stopped
    privileged: true
  mcserver:
    user: "0:0"
    image: itzg/minecraft-server:java17-alpine
    container_name: mcserver
    env_file: .env
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - "./data:/data"
      - "./modpack:/modpack"
      - "./mods:/mods"
      - "./datapacks:/datapacks"
      - "./config:/config"
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 1m
      retries: 20
    labels:
      plugsy.name: "Minecraft server"
      plugsy.icon: "@styled-icons/bootstrap/MinecartLoaded"
      plugsy.category: "Games"