version: "3.8"
services:
  plugsy:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - 9443:9443
    restart: unless-stopped
    privileged: true
  mcserver:
    user: "0:0"
    image: itzg/minecraft-server:java17-alpine
    container_name: mcserver
    env_file: .env
    ports:
      - "47325:25565"
    volumes:
      - "./data:/data"
      - "./modpack:/modpack"
      - "./mods:/mods"
      - "./datapacks:/datapacks"
      - "./config:/config"
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 1m
      retries: 20
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - 32400:32400
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./config_plex:/config
      - /mnt/dde/Series:/tv
      - /mnt/dde/Films:/movies