---
- name: restart
  become: false
  become_user: "{{ username }}"
  community.docker.docker_compose:
    project_src: "/home/{{ username }}/"
    build: no
    restarted: yes
- name: stop_service
  become: false
  become_user: "{{ username }}"
  ansible.builtin.service:
    name: autorestart
    state: stopped
- name: start_service
  become: false
  become_user: "{{ username }}"
  ansible.builtin.service:
    name: autorestart
    state: started
- name: stop
  become: false
  become_user: "{{ username }}"
  community.docker.docker_compose:
    project_src: "/home/{{ username }}/"
    state: absent
