name: Get artifact from id
description: This action download github artifact from id

inputs:
  artifact-id:
    description: Artifact id
    required: true
  output-dir:
    description: Output directory
    required: true
  github-token:
    description: Github token
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Download artifact
      shell: bash
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github-token }}" \
          -o artifact.zip ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/actions/artifacts/${{ inputs.artifact-id }}/zip
    - name: test
      shell: bash
      run: cat artifact.zip
      
    - name: Unzip artifact
      shell: bash
      run: unzip artifact.zip -d ${{ inputs.output-dir }}
    