name: Setup mod
runs:
  using: "composite"
  steps:
    - name: Checkout repository 
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.19'

    - name: Install packwiz
      run: go install github.com/packwiz/packwiz@latest
