name: Setup mod
description: Setup mods
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.19'
        
    - run: go install github.com/packwiz/packwiz@latest
