name = "test"
author = "Moi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cb0aa3d825cb28f1ca8a5243f1853a6e176a032aec49f81246340a22d0a9444"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
