name = "test"
author = "Moi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "078798cdbdb84fe1054f8700590d040b3ba9782e8990cfcb36ea248f6d298a3d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
