name = "test"
author = "Moi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf42d3ab9b4d76a103e27adb4ff7c924ba189cd6e28cc9580cd420b7d432fcb9"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
