name = "test"
author = "Moi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b432c636be4962e12765446e26f7da35bf876c55dd4bb472cf0eb38fb581acfe"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
