name: Ajout mod

on:
  workflow_dispatch:
    inputs:
      name:
        description: Nom du mod
        required: true
      source:
        type: choice
        description: Source du mod
        options:
          - curseforge
          - modrinth
        required: true

jobs:
  AddMod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modpack  

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19'

      - name: Installation de packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Installation du mod ${{ inputs.name }}
        run: | 
          packwiz -y ${{ inputs.source }} install ${{ inputs.name }}
          packwiz refresh

      