name: Ajout mod

on:
  workflow_dispatch:
    inputs:
      name:
        description: Nom du mod
        required: true
      source:
        description: Source du mod
        options:
          - curseforge
          - modrinth

jobs:
  AddMod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19'

      - name: Installtion de packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Installation du mod ${{ input.name }}
      - run: | 
          packwiz ${{ input.source }} install ${{ input.name }}
          packwiz refresh

      