name: Ajout mods

on:
  workflow_dispatch:
    inputs:
      name:
        description: Nom du mod
        required: true
      source:
        type: choice
        description: Source du mod
        options:
          - modrinth
          - curseforge
        required: true

jobs:
  AddMod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modpack
    steps:
      - name: Setup mod
        uses: ./.github/actions/action-setup-mods

      - name: Install ${{ inputs.name }}
        shell: bash
        run: | 
          packwiz -y ${{ inputs.source }} install ${{ inputs.name }}
          packwiz refresh 

      - name: Push mod
        shell: bash
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "ci: install ${{ inputs.name }}"
          git push  

          
      
