name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  Update server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Get config
        run: |
          echo "${{ vars.MINECRAFT_CONFIG }}" > .env
          echo "${{ secret.HOSTS }}" > hosts
          echo "${{ secret.HOSTS }}" > private-key

      - name: Backup
        run: ./bootstrap.sh private-key setup
        with:
          name: backup-$NOW
          path: ./backup/${{ secret.VPS_HOSTNAME }}/home/${{ secret.VPS_USER }}/*
      
      - name: Setup
        run: ./bootstrap.sh private-key setup
      
      - name: Start
        run: ./bootstrap.sh private-key start
