name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  Update-server:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_CUSTOM_ARGS: -i hosts --private-key ./private-key -e "user=${{ secrets.VPS_USER }}" -vv playbook.yml

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Get config
        run: |
          echo "${{ vars.MINECRAFT_CONFIG }}" > .env
          echo "${{ secrets.HOSTS }}" > hosts
          echo "${{ secrets.PRIVATE_KEY }}" > private-key
          chmod +x ./bootstrap.sh
          chmod 600 private-key

      - name: Backup
        run: ansible-playbook --tags="backup" ${{ env.ANSIBLE_CUSTOM_ARGS }}

      - name: Upload backup
        uses: actions/upload-artifact@v3
        with:
          name: backup-$NOW
          path: ./backup/${{ secrets.VPS_HOSTNAME }}/home/${{ secrets.VPS_USER }}/*
      
      - name: Setup
        run: ansible-playbook --tags="setup" ${{ env.ANSIBLE_CUSTOM_ARGS }}
      
      - name: Start
        run: ansible-playbook --tags="start" ${{ env.ANSIBLE_CUSTOM_ARGS }}
