name: CI

on:
  workflow_dispatch:

jobs:

  Update-server:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_CUSTOM_ARGS: -i hosts --private-key ./private-key -e "username=${{ secrets.VPS_USER }} ansible_user=${{ secrets.VPS_USER }}" -vv playbook.yml

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Setup server connection
        uses: ./.github/actions/setup-server-action
        with: backups/${{ secrets.VPS_HOSTNAME }}/home/${{ secrets.VPS_USER }}/*.zip
      
      - name: Setup
        run: ansible-playbook --tags="setup" ${{ env.ANSIBLE_CUSTOM_ARGS }}
      
      - name: Start
        run: ansible-playbook --tags="start" ${{ env.ANSIBLE_CUSTOM_ARGS }}
