name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  Update-server:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Get config
        run: |
          echo "${{ vars.MINECRAFT_CONFIG }}" > .env
          echo "${{ secrets.HOSTS }}" > hosts
          echo "${{ secrets.HOSTS }}" > private-key
          chmod +x ./bootstrap.sh
          chmod 600 private-key

      - name: Backup
        run: ./bootstrap.sh private-key setup

      - name: Upload backup
        uses: actions/upload-artifact@v3
        with:
          name: backup-$NOW
          path: ./backup/${{ secrets.VPS_HOSTNAME }}/home/${{ secrets.VPS_USER }}/*
      
      - name: Setup
        run: ./bootstrap.sh private-key setup
      
      - name: Start
        run: ./bootstrap.sh private-key start
