name: Start server

on:
  workflow_dispatch:
  
jobs:

  Update-server:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_CUSTOM_ARGS: -i hosts --private-key ./private-key -e "username=${{ secrets.VPS_USER }} ansible_user=${{ secrets.VPS_USER }}" -vv playbook.yml

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Setup server connection
        uses: ./.github/actions/action-setup-server
        with:
          minecraft-config: ${{ vars.MINECRAFT_CONFIG }}
          vps-hosts: ${{ secrets.HOSTS }}
          vps-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Setup
        run: ansible-playbook --tags="setup" ${{ env.ANSIBLE_CUSTOM_ARGS }}
      
      - name: Start
        run: ansible-playbook --tags="start" ${{ env.ANSIBLE_CUSTOM_ARGS }}
